### ISSUE TITLE
Carpet duplication

### ISSUE THREAD

**Issue by Hellhium** [fxmorin/carpet-fixes#10]
There seems to be no rule at the moment to prevent carpet duplication 
I know it has been done on other mods (QuickCarpet) but as far as I know it's not compatible with fabric-carpet https://github.com/DeadlyMC/QuickCarpet/commit/e9850b91c8c4cd3c2e000e3e48da30cac0355015

**Comment by FxMorin** [comment]
Actually, the rule `pistonDupingFix` says: `Disable TNT, carpet, and part of rail dupers`
