### ISSUE TITLE
reIntroduceZeroTickFarms Not Working?

### ISSUE THREAD

**Issue by Bootylicious01** [fxmorin/carpet-fixes#105]
Describe the bug:
reIntroduceZeroTickFarms Seems to not be working? Every time i try and use it nothing i do can get it to work i tried it on my server first and did not work but it has a few mods so thought it might be one of them and moved to single player with only fabric api, carpet and carpet fixes and still does not work 

To Reproduce:

Install fabric api, carpet and carpet fixes go into single player and make a farm and the farm will not work at least the one's iv tried 

Expected behavior:

0 Tick farms working

Screenshots

![2022-08-22_04 06 24](https://user-images.githubusercontent.com/72663097/185883892-40909187-57c8-4661-9035-702514d79738.png)

![2022-08-22_04 08 51](https://user-images.githubusercontent.com/72663097/185884397-435eff5b-46de-44fc-bdd9-152093ec9f2e.png)

Minecraft Version
 - 1.19.0
Carpet-Fixes Version
 - 1.19-1.11.2
Carpet Version:
 - 1.19-1.4.79

Additional context

I'm prob just missing something super obvious but i can't think of anything else

**Comment by fxmorin** [comment]
Try in v1.13.0

**Comment by kamanabc123** [comment]
It is not functional in the latest version.

**Comment by fxmorin** [comment]
It will be fixed in the latest release

**Comment by JacktheDevel0per** [comment]
should be closed as complete....
