### ISSUE TITLE
Can't apply changes permanently

### ISSUE THREAD

**Issue by alikindsys** [fxmorin/carpet-fixes#112]
**Describe the bug**
`carpet-fixes` can't load the configuration file nor save to it, making applying changes permanently impossible.

**To Reproduce**
There are two ways to reproduce this behaviour, since this bug report is a combination of two possible paths to achieve it.

Steps to reproduce the behavior (via configuration file):
1. create a configuration file on `world/carpet-fixes.conf` 
2. add any fix to it
3. open the server
4. type `/carpet-fixes`
5. see that the mod didn't load anything

Steps to reproduce the behavior (via in-game commands):
1. set any fix
2. once the mod asks you to set it permanently, click on the message and press enter
3. see the "an unexpected error has occured" 

**Expected behavior**
`carpet-fixes` loads and saves to the per-world permanent settings.

**Screenshots**
![image](https://user-images.githubusercontent.com/36565196/194791360-8bd5d31b-2ff5-4ffa-9ad5-4e3c25f389e8.png)

**Minecraft Version:**
 - 1.19.2
**Carpet-Fixes Version:**
 - v1.12.0
**Carpet Version:**
 - v1.4.83+v220727

**Additional context**
`carpet-fixes` didn't seem to load the per-world configuration file (which seemed to be located at `world/carpet-fixes.conf`) on my local test server, which prompted me to research if i could set those configurations permanently by hand, which would still be a bother but make `carpet-fixes` a part of the [server-side modpack](https://github.com/roridev/soberana-server-mods).

while trying to set the fixes permanently, the game returned that "An unexpected error occured trying to execute that command", and upon closer inspection that NPE (or most likely, a mixin error, cause there would be **no way** that `this.server` would be null while the mod has loaded).

"net.minecraft.server.MinecraftServer.method_27050(net.minecraft.class_5218)" seems to be the cause of that issue. i currently don't have any tooling configured but could help finding the cause of that bug once i have that setup.

**Comment by alikindsys** [comment]
I can confirm that this bug happens on clean quilt and fabric servers with only `carpet` and `carpet-extras`
![image](https://user-images.githubusercontent.com/36565196/194793182-518b2770-50f4-4dc7-962a-b81dc8cd4592.png)
![image](https://user-images.githubusercontent.com/36565196/194793667-fef6f235-1667-49f0-ad4e-eac96adeb3eb.png)

**Comment by FxMorin** [comment]
@adryd325

**Comment by adryd325** [comment]
will get to fixing this shortly

**Comment by FxMorin** [comment]
Fixed in latest release
