### ISSUE TITLE
beeDupeFix prevents bees from entering hives

### ISSUE THREAD

**Issue by SplendidAlakey** [fxmorin/carpet-fixes#116]
**Describe the bug**

Setting `beeDupeFix` to `true` causes bees to ignore beehives. The bug itself was deemed invalid by Mojang, since the reporter was using a modded client https://bugs.mojang.com/browse/MC-234471. Perhaps the rule is unnecessary?

**To Reproduce**

1. Put `beeDupeFix true` in your default carpet fixes config file
2. Create a new world or enter an existing one
3. Place down a beehive, some flowers and spawn bees
4. Observe bees either completely ignore the hive or just bump into it, but fail to enter; normally they fly away

For convenience, you can use /tick warp 7200 after spawning bees.

**Expected behavior**

Bees should be able to enter hives.

**Logs**

https://gist.github.com/SplendidAlakey/867a5f36268eed8dd7ecca608378cf10

**Minecraft Version:**
 - 1.19.2
**Carpet-Fixes Version:**
 - v1.12.2
**Carpet Version:**
 - v1.4.84

**Comment by FxMorin** [comment]
Should be fixed in v1.13.0
