### ISSUE TITLE
hardcodedSeaLevelFix causes a crash with Depth Meter from Additional Additions

### ISSUE THREAD

**Issue by SplendidAlakey** [fxmorin/carpet-fixes#117]
**MC** 1.19.2
**FAPI*** 0.66.0
**Carpet Fixes** 1.12.2
**[Additional Additions](https://www.curseforge.com/minecraft/mc-mods/additional-additions/files/4022435)** 5.1.0

To reproduce:

1. Set `hardcodedSeaLevelFix true` in carpet fixes config
2. Create a world
3. Give yourself or search in creative inventory a depth meter (which is weird, considering you don't even need to actually have the item)
4. Crash

Logs: https://gist.github.com/SplendidAlakey/8e40d2ab6b0fd9319468accec755473c

**Comment by FxMorin** [comment]
Should be fixed in v1.13.0
