### ISSUE TITLE
MC versions set incorrectly on modrinth

### ISSUE THREAD

**Issue by ChristopherHaws** [fxmorin/carpet-fixes#121]
**Describe the bug**
The new version of carpet-fixes on Modrinth is incorrectly set to be compatible with Minecraft 1.19-1.19.3 which breaks mod updaters such as PrismLauncher and Packwiz:
https://modrinth.com/mod/carpet-fixes/version/v1.13.0

If you could update this to be just for 1.19.3 that would be great!

Thanks!

**Comment by FxMorin** [comment]
Fixed, Minecrafts stupid sub version stuff is breaking all my automation
