### ISSUE TITLE
[MC-258561] - Endermen teleport away instead of taking damage from end crystal, TNT and wither skull explosions

### ISSUE THREAD

**Issue by GabrielxDuO** [fxmorin/carpet-fixes#123]
**Does your bug have a Mojira id? If so, what is it?**
It's [MC-258561](https://bugs.mojang.com/browse/MC-258561).

**What's the bug about? Why do you want it fixed?**
Almost all of the wither rose farms based on wither and enderman don't work anymore in 1.19.3.

**Describe the solution you'd like**
Let enderman take damage from explosion like they did in 1.19.2 and before.

**What should the rule be called?**
endermanDontTakeExplosionDamageFix

**Comment by fooeyround** [comment]
Close as complete?
