### ISSUE TITLE
entityBlockCollisionUsingCenterFix disables Players Bouncing on Slime Blocks

### ISSUE THREAD

**Issue by christofkern** [fxmorin/carpet-fixes#127]
**Describe the bug**

**To Reproduce**
1. Enable entityBlockCollisionUsingCenterFix
2. Drop on a Slimeblock from some Distance
3. See that you aren´t bouncing

**Expected behavior**
The Player should bounce

**Minecraft Version:**
 - 1.19.3
**Carpet-Fixes Version:**
 - v1.13.0
**Carpet Version:**
 - v1.4.91

**Comment by ghost** [comment]
also broken in 1.18.2

**Comment by FxMorin** [comment]
This is being removed in the next release
