### ISSUE TITLE
Fabric 1.19.2 - Very heavy load on the server

### ISSUE THREAD

**Issue by MrJorman** [fxmorin/carpet-fixes#129]
I started the Spark profiler, and after a while I got the results in the mods department.

Version carpet fixes: carpet-fixes-1.19-1.12.2.jar

https://spark.lucko.me/MtZJywWkwll
![Безымянный](https://user-images.githubusercontent.com/55187962/215670987-23a94a79-0c48-4195-bf7c-12ac5b5b42ed.png)

**Comment by MrJorman** [comment]
my settings, carpet-fixes.conf

stringDupeFix true
optimizedHypot true
duplicateBlockUpdatesFix true
optimizedRounding true
optimizedPoweredRails true
breakSwapGeneralItemDupeFix true
tripwireHookDupeFix true
pistonDupingFix false
optimizedBiomeAccess true
optimizedRecipeManager true

**Comment by MrJorman** [comment]
and carpet.conf

shulkerSpawningInEndCities true
leadFix true
renewableDragonHead true
piglinsSpawningInBastions true
optimizedTNTHighPriority true
creeperBlockDamage none
railDupingFix true
optimizedFastEntityMovement true
fastRedstoneDust true
sandDupingFix true
renewableElytra 0.1
optimizedHardHitBoxEntityCollision true
quickHarvesting true
renewableDragonEgg true
lagFreeSpawning true
maxEntityCollisions 1
tntDupingFix true

**Comment by FxMorin** [comment]
Please only post performance data if you actually understand what you are doing.
Carpet-Fixes replaces some of the servers main class. Making it seem like carpet-fixes is taking up a lot of performance, its not.
Carpet-Fixes actually takes up nearly no performance
