### ISSUE TITLE
Update to 1.19.4

### ISSUE THREAD

**Issue by Notoriousi** [fxmorin/carpet-fixes#133]
**Is your feature request related to a problem? Please describe.**
carpet-fixes crashes 1.19.4

Log:
https://mclo.gs/LDH3PdZ

**Comment by xFedee** [comment]
https://mclo.gs/s6PwKO7

**Comment by lighthal** [comment]
Any progress?

**Comment by Notoriousi** [comment]
I'm afraid it won't be updated. Unsure where and if future updates will happen.

> Updated to v1.19.3 - This is the last time im doing an update myself

**Comment by FxMorin** [comment]
v1.14.0 is now out
