### ISSUE TITLE
Crash on startup 1.19.4

### ISSUE THREAD

**Issue by SuperRicky14** [fxmorin/carpet-fixes#140]
**Describe the bug**
I have no other mods installed except for carpet and carpet-fixes

**To Reproduce**
1. Install fabric, carpet and carpet fixes
2. Launch the game

**Expected behavior**
Game does not crash

**Screenshots**

**Minecraft Version:**
 - 1.19.4
**Carpet-Fixes Version:**
 - v1.8.8
**Carpet Version:**
 - v1.4.101

**Additional context**
Log: https://mclo.gs/c563kDG
I have tried with carpet version v1.4.100 and still recieved the same error

**Comment by fooeyround** [comment]
Does this fix it? https://github.com/fxmorin/carpet-fixes/releases/tag/v1.14.1
