### ISSUE TITLE
1.19.4 carpet-tis-addition incompatible

### ISSUE THREAD

**Issue by hexadec1mal** [fxmorin/carpet-fixes#142]
https://github.com/TISUnion/Carpet-TIS-Addition
When i launch minecraft with carpet-fixes and carpet-tis-addition it crashes
If i remove carpet-fixes or carpet-tis-addition minecraft launch normally
I use latest version of fabric and all mods
[latest.log](https://github.com/fxmorin/carpet-fixes/files/11787756/latest.log)

**Comment by VodoGamer** [comment]
fixed in https://github.com/TISUnion/Carpet-TIS-Addition/issues/106#issuecomment-1607007219
