### ISSUE TITLE
Update skipper not working 1.20.1

### ISSUE THREAD

**Issue by nelifs** [fxmorin/carpet-fixes#145]
**Describe the bug**
Update suppression not working, redstone dust just breaking when placing on trapdoor

**To Reproduce**
1. Build new small update suppressor
2. Place redstone dust on trapdoor

**Expected behavior**
Update suppressor work

**Screenshots**

**Minecraft Version:**
 - 1.20.1
**Carpet-Fixes Version:**
 - v1.15.2
**Carpet Version:**
 - v1.4.112

**Additional context**

**Comment by FxMorin** [comment]
Thats called a Update skipper, not suppressor.

It was patched in 1.20, are you asking me to unpatch it?

**Comment by nelifs** [comment]
my bad, i didn't know correct name. Is there any way to make it work on 1.20.1? If not, sorry for false bug report :)

**Comment by FxMorin** [comment]
Not currently
