### ISSUE TITLE
reIntroduceInstantBlockUpdates and reIntroduceItemShadowing not working on 1.20-1.20.1

### ISSUE THREAD

**Issue by m1yokko** [fxmorin/carpet-fixes#146]
![изображение_2023-06-28_210004804](https://github.com/fxmorin/carpet-fixes/assets/138043622/297c213d-4127-4ab0-806d-6e702403d14a)
I built a suppressor on 1.20 using rules written in the title but it's not working, redstone dust just destroys after putting it on trapdoor. Fix this ASAP please.

**Comment by FxMorin** [comment]
#145
This is update skipping, not update suppression, also it was patched by Mojang

**Comment by m1yokko** [comment]
But it works on 1.19

**Comment by FxMorin** [comment]
Yes Mojang patched it in 1.20
