### ISSUE TITLE
[MC-105103] - You don't take fall damage when riding 1.9+ boat off a high area

### ISSUE THREAD

**Issue by xXRinzlerrXx** [fxmorin/carpet-fixes#147]
minecraft 1.20.1 + fabric 0.14.21 + fabric api 0.84.0 + fabric carpet 1.20-1.4.112+v230608

**Does your bug have a Mojira id? If so, what is it?**
It's [[MC-105103](https://bugs.mojang.com/browse/MC-105103)

**What's the bug about? Why do you want it fixed?**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [there is no fall damage and the boat is not destroyed]

**Described the solution you'd like**
everything is implemented in the boat-fall 

****Describe alternatives you've considered**can you add a fix from the boat full mod (https://modrinth.com/mod/boat-fall), it's implemented there like it should, but alas, the carpet fixes and boat fall fix mods don't work together

**Comment by FxMorin** [comment]
Ive already fixed this, the rule is called: **boatsDontTakeFallDamageFix**

**Comment by xXRinzlerrXx** [comment]
this file doesn't say anything about fixing this error

I also checked it in the game, when a boat falls from a great height on a flat surface, no damage is done

**Comment by xXRinzlerrXx** [comment]
maybe you meant these fixes: MC-98160, MC-119369

**Comment by FxMorin** [comment]
Oh right that fixes MC-98160
Alright ill add it to my todo list

**Comment by xXRinzlerrXx** [comment]
thanks

**Comment by ghost** [comment]
This is already fixed by Carpet Fixes by enabling BoatsDontTakeFallDamageFix.

**Comment by FxMorin** [comment]
> This is already fixed by Carpet Fixes by enabling BoatsDontTakeFallDamageFix.
