### ISSUE TITLE
The server crashes if Cardboard is installed

### ISSUE THREAD

**Issue by mrElken** [fxmorin/carpet-fixes#149]
https://github.com/CardboardPowered/cardboard

Server version - 1.19.2

Installed mods:
Fabric API
iCommon API
Cardboard
Carpet
Carpet-Fixes

If I remove the "Carpet-Fixes" or  "Cardboard", the server starts up normally
Logs:
[Crash Log.log](https://github.com/fxmorin/carpet-fixes/files/11970501/Crash.Log.log)

**Comment by FxMorin** [comment]
Should be fixed in v1.16.1
