### ISSUE TITLE
Crash with chest-dropper

### ISSUE THREAD

**Issue by LionPa** [fxmorin/carpet-fixes#153]
**Describe the bug**
Crash server when use bugged chest-dropper

**To Reproduce**
Check Video https://youtu.be/0CefhoolxdM

**Expected behavior**
Nothing or dropping item

**Minecraft Version:**
 - 1.20.1
**Carpet-Fixes Version:**
 - v1.16.1
**Carpet Version:**
 - v230608
 
Crash report: [crash-2023-07-20_21.18.04-server.txt](https://github.com/fxmorin/carpet-fixes/files/12109341/crash-2023-07-20_21.18.04-server.txt)

**Comment by FxMorin** [comment]
Why would this be caused by Carpet-Fixes?
