### ISSUE TITLE
[MC-2157] - Particles emitted from dragon egg when teleporting are not pointing in the correct direction

### ISSUE THREAD

**Issue by ghost** [fxmorin/carpet-fixes#154]
**Does your bug have a Mojira id? If so, what is it?**
It's [MC-2157](https://bugs.mojang.com/browse/MC-2157)]

**What's the bug about? Why do you want it fixed?**
When you cause a dragon egg to teleport (such as by clicking on it), the teleportation particles point in a random direction and not to the actual location of the dragon egg.

**Describe the solution you'd like**
Particles produced from a dragon egg upon interacting with it would point in the direction of where the egg was teleported to.

**Additional context**
Attached a video showing how it used to work in 1.2.5, [MC-2157 How it used to work in 1.2.5.mp4](https://bugs.mojang.com/secure/attachment/392713/392713_MC-2157+How+it+used+to+work+in+1.2.5.mp4)

**What should the rule be called?**
You don't need to make one if you don't want to, just helps me make these fixes faster!
DragonEggParticleFix

**Comment by FxMorin** [comment]
Carpet-Fixes only fixes server-side bugs.
