### ISSUE TITLE
Update to 1.20.2

### ISSUE THREAD

**Issue by sqdAva** [fxmorin/carpet-fixes#159]
Pls update to 1.20.2. The [fabric-carpet](https://github.com/gnembon/fabric-carpet/releases/tag/1.4.118) release has already been released

**Comment by Caleb-A-K** [comment]
please do this

**Comment by petersv5** [comment]
If noone else is working on this I have a very quick and dirty port to 1.20.4. I can send a PR next week to get the ball rolling.

**Comment by FxMorin** [comment]
@petersv5 That would be very helpful as I dont have the time to do it currently.
You can remove the update suppression rules as TIS is maintaining working ones.

**Comment by petersv5** [comment]
Initial PR submitted. There are a couple of issues that I would need help resolving, listed in the PR.
