### ISSUE TITLE
End Portal Falling Block Duper not working

### ISSUE THREAD

**Issue by R4z0rX** [fxmorin/carpet-fixes#162]
**Describe the bug**
End Portal Falling Block Duper doesn't work with setting **pistonsPushEntitiesBehindThemFix** set to _true_.
The setting **fallingBlockDuplicationFix** was _false_.
The machine work as expected if I just set **pistonsPushEntitiesBehindThemFix** to _false_.

**Minecraft Version:** 1.20.1
**Carpet-Fixes Version:** v1.20-1.16.1
**Carpet Version:** v1.4.112+v230608

**Additional context**
The duper design is from Sorpio:
[FAST Sand Duper (72k/hour) | Minecraft | Java 1.18+](https://www.youtube.com/watch?v=h5310T1ie1I)

**Comment by FxMorin** [comment]
Ill be honest here, this is kinda of cool.
It means pistons always push more than a block backwards and that some duper designs use it. 

Technically that's how this fix is suppose to work, preventing the piston from pushing more than a block. So I wont be fixing this one for now

**Comment by R4z0rX** [comment]
Yeah, I know, I just wanted to report it, 'cause now it's kinda redundant.
Maybe, you could clarify this somewhere.
