### ISSUE TITLE
Crashes on Launch

### ISSUE THREAD

**Issue by RealmKebab** [fxmorin/carpet-fixes#165]
**Describe the bug**
My client crashes on launch 

**To Reproduce**
1. Use my modlist (provided in the mclogs file)
2. Try to launch the game
3. Game crashes

**Expected behavior**
the game not suppose to crash

**Screenshots**

**Minecraft Version:**
 - 1.20.1
**Carpet-Fixes Version:**
 - v1.17.0
**Carpet Version:**
 - v1.4.112

**Additional context**
https://mclo.gs/k0T373K

**Comment by Player505** [comment]
#164
