### ISSUE TITLE
Comparator bug in Update Supression

### ISSUE THREAD

**Issue by DeepResonanceHub** [fxmorin/carpet-fixes#170]
**Description**
On version 1.20.1, when the compressor was triggered, the comparator remained suspended in the air when the hatch was opened, available for interaction. It was also updated as a regular comparator, allowing you to create shadow objects. However, on version 1.20.4, it crashes immediately after opening the hatch, and only the phantom block remains, which is also not updated.

**To Reproduce**
1. Go on 1.20.4
2. Start with CARPET and CARPET FIXES 
3. Set normal update suppression settings.
4. Reproduce my moves.

**Expected behavior**
I expected to see that the comparator would not fall out and would remain hanging on the hatch, capable of being updated without destruction.

**Screenshots**
![image](https://github.com/FxMorin/carpet-fixes/assets/87901025/7214c298-c0c4-43ef-b6e3-cb8a56a22dcf)

**Minecraft Version:**
 - 1.20.4
**Carpet-Fixes Version:**
 - v1.17.0
**Carpet Version:**
 - v1.20.3-1.4.128+v231205

**Additional context**
Sorry, I'm not very good in English.

**Comment by silverfox0000** [comment]
Do you fixed it or not? If yes, what you do to fix it?
I got same problem

**Comment by Crystal0404** [comment]
> Do you fixed it or not? If yes, what you do to fix it? I got same problem

This is in line with expectations, I think 1.20.4 should do that(At least 1.20.5 it works)
![2024-04-27_16 56 05](https://github.com/FxMorin/carpet-fixes/assets/120556221/054aa817-14cf-496c-bad2-4a8d8a8702dd)
Remove redstone block

**Comment by Crystal0404** [comment]
FxMorin is very busy and may not have time to deal with this, If you need a rule to work around this change

Please try https://modrinth.com/mod/crystalcarpetaddition `/cca ComparatorIgnoresStateUpdatesFromBelow true`(>=1.20.5)

`/cca ComparatorCanPlaceAboveAir true`(1.20.4)

It only works with comparators, and I did it on purpose

If you want repeaters to do the same... I've heard that tis-carpet will introduce more powerful rules to address these issues
https://modrinth.com/mod/carpet-tis-addition
