### ISSUE TITLE
Stutter and server crash on fabric 1.19.2

### ISSUE THREAD

**Issue by kineticV** [fxmorin/carpet-fixes#173]
**Describe the bug**
My dedicated server has intermittent lag when this mod is added, and then it crashes after a few seconds to minutes. Mobs stutter, and I can see in the logs some ticks are taking over 10 seconds. Then when a tick takes 60 seconds the server crashes. When I remove this mod everything works as expected with no lag. Using the spark profiler I found that carpet-fixes is using 85% of the server thread tick time. Screenshot below. When I remove the mod, the average and max MSPT goes way down.

I believe I saw this issue may have been fixed in a later version of this for new versions of Minecraft. Can the fix be ported to 1.19.2? There are multiple popular fabric mods not supported above this version, so many of us are stuck here.

**To Reproduce**
1. Log on to a dedicated server
2. Spawn in a few entities

**Screenshots**
![image](https://github.com/FxMorin/carpet-fixes/assets/53151389/10eb114c-0478-443c-91a7-fe84048e5743)
![image](https://github.com/FxMorin/carpet-fixes/assets/53151389/83523e31-d9d1-4761-8252-6f30b0b601a7)

**Minecraft Version:**
 - Fabric 1.19.2
**Carpet-Fixes Version:**
 - 1.19-1.12.2
**Carpet Version:**
 - 1.19.2-1.4.84+v221018

**Comment by FxMorin** [comment]
This is not due to Carpet-Fixes. We simply wrap the server method.

**Comment by kineticV** [comment]
I have tried adding carpet-fixes and removing it in different situations. I only encounter stuttering and crashes when carpet-fixes is added. Plus spark shows the majority of the tick thread is spent in carpet-fixes catchExceptions. Could it be an interaction with another mod?

**Comment by Crystal0404** [comment]
> 我尝试过添加地毯固定并在不同情况下将其删除。我只在添加地毯修复时遇到卡顿和崩溃。加上 spark 显示大部分 tick 线程都花在了地毯修复 catchExceptions 中。可能是与另一个模组的互动吗？

This is in line with expectations, if you need a detailed explanation, please check this
https://github.com/TISUnion/Carpet-TIS-Addition/issues/136

**Comment by Crystal0404** [comment]
> I have tried adding carpet-fixes and removing it in different situations. I only encounter stuttering and crashes when carpet-fixes is added. Plus spark shows the majority of the tick thread is spent in carpet-fixes catchExceptions. Could it be an interaction with another mod?

This is in line with expectations, if you need a detailed explanation, please check this
https://github.com/TISUnion/Carpet-TIS-Addition/issues/136
