### ISSUE TITLE
Incorrect versions on modrinth

### ISSUE THREAD

**Issue by mdhlp** [fxmorin/carpet-fixes#183]
Carpet fixes v1.17.0 is listed as compatible with MC 1.20, 1.20.1 and 1.20.2, but doesn't actually work on those versions
![IMG_20240728_123619_821](https://github.com/user-attachments/assets/fcd603ad-d30e-467c-903a-80b7e31e2455)
Also, it works on MC 1.20.3, but in the changelog it's said that it's incompatible with MC versions from 1.20 to 1.20.3

**Comment by FxMorin** [comment]
Fixed
