### ISSUE TITLE
saferItemTransfer bug:deletes items

### ISSUE THREAD

**Issue by Jandre144** [fxmorin/carpet-fixes#24]
idk if this is intentional or a bug but: with the saferItemTransfers when firing a dropper into a tile entity that cant except more blocks (a full chest) or cant take a certain item (brewing stand) the item gets delete
![2021-12-13_09 16 16](https://user-images.githubusercontent.com/85630001/145770899-159f8cb2-3d80-4d5e-84c6-b309ec954774.png)

**Comment by FxMorin** [comment]
Can you see if this issue still occurs in v1.5.0
I was unable to reproduce

**Comment by Jandre144** [comment]
yea it seems to be fixed in the v1.5.0, thanks
