### ISSUE TITLE
Swapping Items Deletes them

### ISSUE THREAD

**Issue by Ko0bEy** [fxmorin/carpet-fixes#25]
in the current release version 1.5.0 if I swap an item from the inventory to my hotbar, any item that was in that hotbar slot disappears.
Setup:
Minecraft 1.18.1, Fabric 0.12.2, Fabric API 0.44.0, Carpet Mod 1.4.56, Carpet fixes 1.5.0+v211215

Edit: Same with a fresh Instance. Newly created world, survival mode

**Comment by FxMorin** [comment]
No rules enabled? Alright, ill look into it. Thanks

**Comment by FxMorin** [comment]
You are right, seems the `reIntroduceItemShadowing` rule was redirecting without adding back the vanilla behavior. I am changing its implementation and should be releasing a v1.5.1 later today. Thanks

**Comment by Ko0bEy** [comment]
Sorry for the bad news XD, thanks for the great mod!

**Comment by FxMorin** [comment]
Alright, it's now in v1.5.1!
