### ISSUE TITLE
Server cannot be joined

### ISSUE THREAD

**Issue by jezekdomi** [fxmorin/carpet-fixes#29]
Hi! :)
I dunno if it's my fault but this mod on 1.18.1 (if in mod folder on server) does not let me join my server. Immediately after removing it, server's joinable. I tried all three (carpet, carpet-extra, carpet-fixes) on both client and server and other combinations but none seem to work.
Thanks

**Comment by FxMorin** [comment]
Would you be able to provide a log file?

**Comment by Cccc-owo** [comment]
Me too,and my server uses [authlib-injector](https://github.com/yushijinhun/authlib-injector) to login.
Here is the log of authlib-injector.
[authlib-injector.log](https://github.com/fxmorin/carpet-fixes/files/7984305/authlib-injector.log)

**Comment by FxMorin** [comment]
Ah, nice. Try using v1.5.x
Should fix your problem. It's been fixed in the upcoming v1.7.0

**Comment by SergeyMC9730** [comment]
I have same problem but i'm not using `authlib-injector` to join. I have set `online-mode` to `false` but server still kicks me out from it

**Comment by FxMorin** [comment]
Can one of you try this: https://github.com/fxmorin/carpet-fixes/suites/5227447658/artifacts/160391117
It should work even if its for 22w05a

**Comment by Cccc-owo** [comment]
> Can one of you try this: https://github.com/fxmorin/carpet-fixes/suites/5227447658/artifacts/160391117 It should work even if its for 22w05a

With this version, my server even failed to start.

This is the log.[latest.log](https://github.com/fxmorin/carpet-fixes/files/8030385/latest.log)

**Comment by SergeyMC9730** [comment]
Try to remove Fabrication and start server again
