### ISSUE TITLE
deop command issue

### ISSUE THREAD

**Issue by Soochaehwa** [fxmorin/carpet-fixes#33]
When the server's op becomes non-operator using the deop command, all players get a message saying "You are not white-listed on this server!" and are kicked from the server

used mod:
carpet-fixes-1.18.1-1.5.1+v220107
fabric-api-0.46.4+1.18
fabric-carpet-1.18.1-1.4.57+v220119
lazydfu-0.1.2
lithium-fabric-mc1.18.1-0.7.7

**Comment by FxMorin** [comment]
What rules do you have enabled on the server?

**Comment by Soochaehwa** [comment]
There were no rules enabled on the server. It was just the default

**Comment by FxMorin** [comment]
Then it's probably not caused by carpet-fixes. This might honestly be a vanilla bug

**Comment by Soochaehwa** [comment]
Finding the cause, the 'toggleEnforceWhitelist' rule was the cause
It was resolved when the default value true was changed to false

**Comment by FxMorin** [comment]
That rule is by default set to the server.properties. So make sure `EnforceWhitelist` is set to false in your server properties.

**Comment by Soochaehwa** [comment]
Yes, the value of enforce-whitelist is false
But the default value for toggleEnforceWhitelist was true
