### ISSUE TITLE
/carpet-fixes reIntroduceItemShadowing doesnt work for me

### ISSUE THREAD

**Issue by endor1231** [fxmorin/carpet-fixes#35]
I tried ItemShadowing but it didnt work. It was all fine but the item was only in the chest that i was using. 
![2022-02-15_15 45 30](https://user-images.githubusercontent.com/99743082/154085758-8624d249-cc22-43bb-9517-ba264c2576ca.png)

I was using this contraption.

**Comment by FxMorin** [comment]
Seems to work for everyone else. Are you using numbers to swap items?
