### ISSUE TITLE
Does carpet fixes modify the behavior of the hopper?

### ISSUE THREAD

**Issue by monsters-97** [fxmorin/carpet-fixes#36]
version ：carpet-fixes-1.18.x-1.7.0+v220301
truely gamerules：reIntroducePortalGeneralItemDupe，reIntroduceDonkeyRidingDupe，reIntroduceZeroTickFarms

When an item flows through the hopper chain, the hopper sucks the item out of the waterway, causing the item sorting waterway to fail. The hopper behaves normally before I add the carpet fixes and after I remove the carpet fixes. So I think it's the carpet fixes that modify the behavior of the hopper. But I don't know exactly which command modified it. It doesn't look like the three game rules I turned on affect the hopper. Is there another carpet fixes rule that affects hopper？

The approximate situation is shown in the figure:
![image](https://user-images.githubusercontent.com/94698335/157922604-615ec93d-7094-4b3e-997b-75c4d8323f46.png)

**Comment by fxmorin** [comment]
Can you list the carpet-fixes & Carpet rules that you have enabled?

**Comment by FxMorin** [comment]
I believe I found the issue, ill release a fix for this. Thanks for reporting it.
I'll need you to test if it works.
Temporary solution: `/carpet-fixes velocityNotCancelledFix true`

**Comment by FxMorin** [comment]
Please tell me if v1.7.1 fixed the issue.
Modifications to vanilla behaviour without active rules is something I take very seriously

**Comment by monsters-97** [comment]
v1.7.1 fixed the issue. Now it works properly. thank you.
