### ISSUE TITLE
chunkSaveCooldownDelay broken 

### ISSUE THREAD

**Issue by HjonkWeGoos** [fxmorin/carpet-fixes#39]
![image](https://user-images.githubusercontent.com/96707407/158938681-691d1b59-4073-4a13-b1b1-1d5e70a82f76.png)
this happens when i try to switch it to any of the numbers it should of worked with idk if it is a bug or not i just dont want to play 1.18.2 with lag

**Comment by FxMorin** [comment]
Have you tried adding `L` after the number?

**Comment by FxMorin** [comment]
Can you please check with the latest release and tell me if you still get the issue, thanks!

**Comment by HjonkWeGoos** [comment]
well uhh this happens now 
![image](https://user-images.githubusercontent.com/96707407/159144829-def842ea-c45e-458d-a1bb-c52ca03cf605.png)
i dont seem to be able to get it to work

**Comment by FxMorin** [comment]
Ehh that should be included inside of the mod, are you sure you are using the right file. Not the sources one

**Comment by HjonkWeGoos** [comment]
ahhh lmao thats what it was

**Comment by HjonkWeGoos** [comment]
i normally just click the top file

**Comment by HjonkWeGoos** [comment]
uhm now the chunkSaveCooldownDelay is getting laggier with a higher number and just stays the same with a lower

**Comment by FxMorin** [comment]
I don't know what to tell you, you need to adjust it based on your needs. I highly doubt that a higher number is causing you lag though. Might want to check what it is

**Comment by FxMorin** [comment]
Well the original issue was fixed, so ill close this issue
