### ISSUE TITLE
Automatic Modrinth github actions

### ISSUE THREAD

**Issue by FxMorin** [fxmorin/carpet-fixes#41]
It's been on my todo list for a while although I just keep on getting busier by the day, so it's time to ask the community again.

I want the publish action to automatically upload the new mod to curseforge & modrinth.
I haven't updated the curseforge page in forever, and never made a modrinth page for the mod.

**Comment by FxMorin** [comment]
Thanks Altrisi for #44, so modrinth is the only one left

**Comment by altrisi** [comment]
Just add the modrinth ID and token to the action, it supports modrinth.

**Comment by FxMorin** [comment]
Thanks @altrisi
