### ISSUE TITLE
Minecart won't rebound

### ISSUE THREAD

**Issue by DewyDewback** [fxmorin/carpet-fixes#43]
Minecarts won't "bounce" off walls and head the other direction on powered rails, instead keeping their momentum and getting stuck. From what I've tested, this isn't a problem with any rule in particular, but is tied to the carpet-fixes mod.
![2022-03-30_21 13 16](https://user-images.githubusercontent.com/102708657/160962476-436d5121-d903-4f07-8ff6-bc7ad3ef7963.png)
.

**Comment by FxMorin** [comment]
Have you tried without carpet-fixes?
If no rule was enabled, this is a severe problem since the mod should be vanilla if no rules are enabled

**Comment by FxMorin** [comment]
What minecraft version, and what carpet-fixes version

**Comment by DewyDewback** [comment]
I've tried disabling everything, and it only fixed when I moved the file out of the mods menu (unless some settings are enabled by default that I don't know about). It's on 1.18.1, and the file is named fabric-carpet-1.18.1-1.4.57+v220119.jar

**Comment by FxMorin** [comment]
Ehh fabric-carpet is not the file I need to know the version of. I need the version of carpet-fixes

**Comment by DewyDewback** [comment]
I'm pretty sure it was 1.4.0

**Comment by FxMorin** [comment]
Ok well then that's really outdated. Try using a more recent version like [1.7.2](https://github.com/fxmorin/carpet-fixes/releases/tag/v1.7.2)
If you still get the issue, then tell me

**Comment by DewyDewback** [comment]
I've just tried it on 1.7.2, and the bug is still there when I disable all of the rules

**Comment by FxMorin** [comment]
Alright ill look into it

**Comment by FxMorin** [comment]
I'm not able to replicate this issue. Can you load up the latest version v1.8.2
https://github.com/fxmorin/carpet-fixes/releases
& see if you can recreate it there.
Also are you using any other mods than just carpet?
