### ISSUE TITLE
minecart bug 0 carpet fixes rules activated

### ISSUE THREAD

**Issue by miguelguerra1907187** [fxmorin/carpet-fixes#45]
i dont know why but when i install the mod all the hopper minecarts dont bounce back on the wall(stone) anymore , when i uninstall they work again, and i dont have any carpet fixes rule activated.    1.18  mod version 1.7.0 v220301

**Comment by FxMorin** [comment]
Please give me the mod version & mc version

**Comment by miguelguerra1907187** [comment]
> 

I added on the msg above (i edit the msg)

**Comment by FxMorin** [comment]
Can you try https://github.com/fxmorin/carpet-fixes/releases/tag/v1.7.3
