### ISSUE TITLE
playerBlockCollisionUsingCenterFix is buggy

### ISSUE THREAD

**Issue by KosmX** [fxmorin/carpet-fixes#46]
When enabled, the fall speed is calculated incorrectly.

Reproduce:
Enable this *fix*, place a floating block in the air, stand on it, then just walk down.
You'll have an initial velocity

Or jump in a 2 height place, your y velocity won't be set to 0 when reaching the roof. (easier to see with jump boost effect)

> It works with other entities too, The player is the easiest to control.

Used: Carpet 1.4.69
Carpet-fixes: 1.18.x-1.7.4-v220408

**Comment by FxMorin** [comment]
Ah yup I think I know what's causing that, I'm adding the velocity from air which I shouldn't be.
I'll fix it today

**Comment by FxMorin** [comment]
Should have been fixed with [commit](https://github.com/fxmorin/carpet-fixes/commit/1437631916cc13fb0116925a93a9354b4589ee55)
I'll hopefully be releasing a version with the fix soon

**Comment by FxMorin** [comment]
Should be fixed in the latest releases!
