### ISSUE TITLE
OptimizedRecipeManager doesn't allow crafting of certain items

### ISSUE THREAD

**Issue by QPCrummer** [fxmorin/carpet-fixes#48]
Certain items show up in the recipe book, but when placed in a crafting table, they don't generate an output. 

Items that I have found that do this:
- Bows
- Fishing Rods
- Hoppers
![2022-04-10_14 25 07](https://user-images.githubusercontent.com/66036033/162634011-680db59a-caf8-4905-bae5-7bc0949a5a14.png)
![2022-04-10_14 25 12](https://user-images.githubusercontent.com/66036033/162634012-4546c02a-fc7d-4d03-b073-f3209d3acb45.png)
![2022-04-10_14 25 17](https://user-images.githubusercontent.com/66036033/162634013-1fbef844-4662-45a0-aa0b-2d86cf8573bb.png)

**Comment by FxMorin** [comment]
Thanks, ill look into this soon

**Comment by QPCrummer** [comment]
Thanks

**Comment by SandWoodJones** [comment]
It also prevents dying armor
![image](https://user-images.githubusercontent.com/35671374/174498372-eb6666f7-2f9d-4f60-937e-c6bdedd89339.png)
