### ISSUE TITLE
fix for MC-124177

### ISSUE THREAD

**Issue by misaka4a92** [fxmorin/carpet-fixes#50]
see [Debugify](https://github.com/W-OVERFLOW/Debugify/blob/1.18/common/src/main/java/cc/woverflow/debugify/mixins/basic/server/mc124177/ServerPlayerEntityMixin.java) and [FabricCrossDimTPFix](https://github.com/CodedSakura/FabricCrossDimTPFix/blob/master/src/main/java/eu/codedsakura/fabriccrossdimtpfix/mixin/TPMixin.java#L23) implementations

**Comment by FxMorin** [comment]
I'm not a fan of copying other people's code. So ill look into it myself

**Comment by FxMorin** [comment]
Good thing that I did too, they're both doing it wrong xD
I'll be committing the fix soon, I'm guessing you want this for 1.18.2 so ill cherry-pick it to that branch also

**Comment by FxMorin** [comment]
Fixed in: https://github.com/fxmorin/carpet-fixes/commit/2fc1cc39272b55a65c49349e94492b8c2fc971f3
It will be available as the rule `crossDimensionTeleportLosesStatsFix` in the next release

**Comment by FxMorin** [comment]
It's been released in both v1.7.6 (1.18) & v1.8.7 (22w14a)

**Comment by misaka4a92** [comment]
Thank you! Your fix is wonderful! Before that I could only mix the use of these two mods to sync the experience level after I entered a new dimension, thinking that these implementations might help to fix this bug. Now there is a better solution for this problem.

**Comment by misaka4a92** [comment]
carpet-fixes 1.7.6+v220420 crossDimensionTeleportLosesStatsFix works on 1.18.2
