### ISSUE TITLE
incorrectExplosionExposureFix makes all explosions fail to interact with entities

### ISSUE THREAD

**Issue by Minepig** [fxmorin/carpet-fixes#51]
When I enabled incorrectExplosionExposureFix, all explosion cannot push or damage entity (actually damage only a little bit).

I think I have found the problem:
(In file carpet-fixes/src/main/java/carpetfixes/mixins/coreSystemFixes/Explosion_exposureMixin.java)
```java
@Mixin(Explosion.class)
public class Explosion_exposureMixin {
    private static void getExposure(Vec3d source, Entity entity, CallbackInfoReturnable<Float> cir) {
        if (CFSettings.incorrectExplosionExposureFix) {
            /* something */
            if (!(d < 0.0D) && !(e < 0.0D) && !(f < 0.0D)) {
                /* something */
                cir.setReturnValue((float)i / (float)j);
            }
            cir.setReturnValue(0.0F);
        }
    }
}
```
Doesn't it mean that all the calls to this method would return 0.0f?

I'm sorry that I can't send PR because I'm not familiar with modding. :(

**Comment by FxMorin** [comment]
You don't need to tell me where the issue is, you just need to tell me the issue, and ill fix it. I need to fix one more bug today and then ill fix this one
