### ISSUE TITLE
[1.18.2] Crashes on startup

### ISSUE THREAD

**Issue by pewblaze** [fxmorin/carpet-fixes#53]
Tried to start my game today & it crashes on startup. Not sure why, got a lot of mods ^^" 

Fabric 1.18.2 - Loader 0.13.3
carpet-fixes-1.18.x-1.7.6+v220420

[latest.log](https://github.com/fxmorin/carpet-fixes/files/8542966/latest.log)

**Comment by FxMorin** [comment]
geez louise, you weren't kidding about having a lot of mods. So many conflicts, I can fix this one tho. Should be in the next release. Which might be out in a day or a week idk

**Comment by pewblaze** [comment]
Sorry D; The game runs though ^^" & thanks! ^^
