### ISSUE TITLE
QuickCarpet Edition

### ISSUE THREAD

**Issue by Xiaohuang257** [fxmorin/carpet-fixes#54]
https://www.curseforge.com/minecraft/mc-mods/quickcarpet

**Comment by FxMorin** [comment]
Do you realize how much work that's going to be?

**Comment by FxMorin** [comment]
Pfffff who am I to complain, I fix bugs.
Ask and you shall receive: [quickcarpet-fixes](https://github.com/fxmorin/quickcarpet-fixes)
