### ISSUE TITLE
Item Shadowing breaking when the player logs off

### ISSUE THREAD

**Issue by DewyDewback** [fxmorin/carpet-fixes#57]
The ReIntroduceItemShadowing rule breaks item shadowing when the player logs off with the shadowed items in a chest (not including spawn chunks on a server for some reason, even when restarted) in their e-chest, or in their inventory.
Strangely, it doesn't break when leaving the chunks, only when you log off. I don't know anything about coding for mods, but I would guess that it means the problem is client-side instead of server-side. I also don't use blanket, so if that fixes the problem, let me know.

De-shadowing in the inventory matches up with how it worked in 1.17, but in that version it stayed shadowed when put in an e-chest or regular chest. This severely limits it's use, as you either have to re-shadow or go back to spawn every time you want to shadow an item.

I've included a world download with an update suppressor set up to demonstrate the problem, and this was all tested on the latest 1.18 version of the mod.
I'd appreciate if this was fixed, but it's probably not the most urgent problem to solve, so feel free to just add a note and work on other things
[Item shadowing problem.zip](https://github.com/fxmorin/carpet-fixes/files/8618479/Item.shadowing.problem.zip)
.

**Comment by FxMorin** [comment]
You just described the vanilla behaviour.
If you want to make it persistent, use this mod: https://github.com/mattymatty97/carpet-shadow
