### ISSUE TITLE
[1.18.2] Issue with tagKeyMemoryLeakFix

### ISSUE THREAD

**Issue by itsdinkd** [fxmorin/carpet-fixes#58]
https://github.com/TechReborn/TechReborn/issues/2947 

Turned on tagKeyMemoryLeakFix on my modpack's (another quality modpack 2) official server and it disconnected everyone on join, and pretty much broke tags to the point where Tech Reborn could not find the required tags, forcing the disconnects. 

More info can be found on the issue above with logs and such.

**Comment by Ayutac** [comment]
Is tagKeyMemoryLeakFix a TR thing?

**Comment by FxMorin** [comment]
I've commented on the tech reborn report. I highly recommend they fix it from there end since 1.19 uses this exact fix!

**Comment by itsdinkd** [comment]
Fingers crossed it gets fixed, looks like an important thing to have enabled.

**Comment by FxMorin** [comment]
Fixed in v1.7.7 for 1.18.x

**Comment by itsdinkd** [comment]
Thanks fx. So I can use taglock fix now and it will not crash right? It just skips tech reborn?

**Comment by FxMorin** [comment]
nope it can't run with techreborn. If you don't have the techreborn mod, it will work fine.
Otherwise you will just not be able to use the rule

**Comment by itsdinkd** [comment]
Oh damn. I use tech reborn in my pack, so I pretty much cannot run this command at all then? What was fixed?

**Comment by FxMorin** [comment]
The fix was to prevent anyone from running that command if techreborn is being used. Should be fine, will just be vanilla instead
