### ISSUE TITLE
optimizedRecipeManager breaks furnaces

### ISSUE THREAD

**Issue by RealityTest** [fxmorin/carpet-fixes#59]
I'm using the latest version for 1.18.2

I tested it on two different servers and on both enabling the setting "optimizedRecipeManager" would break furnaces: They just don't smelt anything. As soon as I disable the setting they work again.

**Comment by Minfrog314** [comment]
Same here. I had a bunch of other mods and it made it very hard to troubleshoot.
I thought it would have been the optimize furnace setting, but it wasnt.

**Comment by FxMorin** [comment]
This has been fixed internally and should be committed today. I may be releasing a version with the fix today.
