### ISSUE TITLE
Book Duping

### ISSUE THREAD

**Issue by angrynerd** [fxmorin/carpet-fixes#6]
Hello, given that most other duplication glitches have fixes in this mod, i would greatly appreciate if the book duplication glitch that is done with the popbob mod be fixed as well. I'm not versed enough in how this dupe works or how to write a mod to add this myself unfortunately, but i have seen it done on my server before and it is a problem. If not i understand, but i figured that given most other duplication methods are patched woth this mod that it could make sense to be included. Thanks in advance for any response to this issue.

**Comment by fxmorin** [comment]
Sounds good could you link me to the mod or explanation on how it works?

**Comment by angrynerd** [comment]
Yes, this isn't the best video on it but its the first dupe in the video otherwise known as the .d dupe. Apparently its fixed in most paper and spigot servers but not fabric. https://youtu.be/U-p2DCF5Qv0

**Comment by angrynerd** [comment]
From the sounds of it it causes the book data to overflow crashing the client and not saving their inventory. This means that when they join their inventory reverts back and what ever items they offloaded will be in both places.

**Comment by fxmorin** [comment]
Oh that one
Ya I already fixed that, the rule is called: `chunkRegenFix`

**Comment by angrynerd** [comment]
Oh cool! I did not know that was already fixed! Thank you!
