### ISSUE TITLE
Carpet-Fixes Incompatibility with Easy-Magic

### ISSUE THREAD

**Issue by MaranRoseGIT** [fxmorin/carpet-fixes#62]
**_Fabric 1.18.2_**

Log of Issue: [https://pastebin.com/z2iEcU5W](url)

I don't have much else information for this one, it appears that Easy-Magic is the issue. I don't see any other mods that are causing this issue.

**Comment by FxMorin** [comment]
**Fixed in these releases:**
- [22w14a](https://github.com/fxmorin/carpet-fixes/releases/tag/v1.8.9)
- [1.18.x](https://github.com/fxmorin/carpet-fixes/releases/tag/v1.7.8)
