### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by QPOZP** [fxmorin/carpet-fixes#63]
**Describe the bug**
Carpet-Fixes 1.7.7 in Minecraft 1.18.2 in Java 18.0.1 with Fabric 0.14.5 on PolyMC 1.2.2 crashes during startup

**To Reproduce**
1. Install Java 18.0.1
2. Download PolyMC
3. Download Minecraft with Fabric
4. Install Carpet and Carpet-fixes
5. Launch

**Expected behavior**
Not crash

**Screenshots**

**Minecraft Version:**
 - 1.18.2
**Carpet-Fixes Version:**
 - v1.7.7
**Carpet Version:**
 - v1.4.69

**Additional context**
[log](https://0x0.st/ommA.txt)

**Comment by FxMorin** [comment]
Oh, polyMc the launcher. Thought you meant polyMc the mod xD _That confusing_
I'll look into it

**Comment by FxMorin** [comment]
**Fixed in these releases:**
- [22w14a](https://github.com/fxmorin/carpet-fixes/releases/tag/v1.8.9)
- [1.18.x](https://github.com/fxmorin/carpet-fixes/releases/tag/v1.7.8)
