### ISSUE TITLE
still crashing on startup with 1.7.8

### ISSUE THREAD

**Issue by PweSol** [fxmorin/carpet-fixes#64]
**Describe the bug**
Both `carpet-fixes-1.18.x-1.7.8` and `carpet-fixes-1.18.x-1.7.7` are crashing the game on startup. 
`carpet-fixes-1.18.x-1.7.6+v220420` does not crash.
Doesn't seem to be a mod conflict(?).

**To Reproduce**
1. Update from 1.7.6 to 1.7.8
2. The game crashes

**Expected behavior**
Game not crashing.

**Screenshots**

**Minecraft Version:**
 - 1.18.2
**Carpet-Fixes Version:**
 - v1.7.8
**Carpet Version:**
 - v1.4.69

**Additional context**
[minecraft.log](https://github.com/fxmorin/carpet-fixes/files/8656371/minecraft.log)

**Comment by FxMorin** [comment]
Seems a mod is modifying WolfEntity. Do you have any other bug fix mods?
`Critical injection failure: Variable modifier method modifyAmount(F)F in carpet-fixes.mixins.json:entityFixes.WolfEntity_snowballDamageMixin from mod carpet-fixes failed injection check, (0/1) succeeded.`

**Comment by PweSol** [comment]
`Blanket Client tweaks-1.0.3` and `TieFix-1.10.0`
I also have a bunch of performance mods such as lithium.

**Comment by FxMorin** [comment]
Well, its neither of the fix mods. Give me a bit to do some compatibility checking, since the mod works fine without any other mods

**Comment by PweSol** [comment]
So do you want me to give you my whole list of 56 mods? Most of them are performance mods, few qol and some cosmetic. The rest are dependencies.

**Comment by FxMorin** [comment]
No it's fine, its in the log

**Comment by PweSol** [comment]
It could have been even more if the rest was updated to 1.18.2 :D

**Comment by FxMorin** [comment]
I hate how it closes issues automatically when I submit a fix. Give me a sec ill give you a download

**Comment by FxMorin** [comment]
Can you tell me if this fixes the issue: https://github.com/fxmorin/carpet-fixes/suites/6439371389/artifacts/235684127

**Comment by PweSol** [comment]
Yes it works! That was fast! You have my respect :D Time to play around with all the new additions :)

**Comment by FxMorin** [comment]
your welcome
