### ISSUE TITLE
Game Crashes

### ISSUE THREAD

**Issue by WOCOWZj** [fxmorin/carpet-fixes#66]
**Describe the bug**
The game crashes when booting with the mod.

**To Reproduce**
1. Install Minecraft 1.18.2 with fabric. (I can boot the game on my PC. And fabric is installed automatically by PCL launcher. )
2. Download this mod carpet-fixes 1.18.2-1.7.8 and fabric-api and carpet.
3. Boot the game (I am used to using PCL launcer. However when using HMCL launcher it performed the same.)

**Expected behavior**
Boot the game correctly and be able to use commands like /carpet

**Minecraft Version:**
 - 1.18.2
**Carpet-Fixes Version:**
 - v1.7.8
**Carpet Version:**
 - v1.4.69

**Additional context**
Here's my crash report:

> [20:59:52] [main/INFO]: Loading Minecraft 1.18.2 with Fabric Loader 0.14.5
> [20:59:52] [ForkJoinPool-1-worker-2/WARN]: Mod carpet-fixes uses the version 1.18.x-1.7.8 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'x'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
> [20:59:52] [main/INFO]: Loading 50 mods:
> 	- carpet 1.4.69
> 	- carpet-fixes 1.18.x-1.7.8
> 	- com_github_llamalad7_mixinextras 0.0.6 via carpet-fixes
> 	- conditional-mixin 0.1.5 via carpet-fixes
> 	- fabric 0.51.1+1.18.2
> 	- fabric-api-base 0.4.4+d7c144a860 via fabric
> 	- fabric-api-lookup-api-v1 1.6.0+2373a54560 via fabric
> 	- fabric-biome-api-v1 8.0.4+7b0f312660 via fabric
> 	- fabric-blockrenderlayer-v1 1.1.12+3ac43d9560 via fabric
> 	- fabric-command-api-v1 1.1.9+d7c144a860 via fabric
> 	- fabric-commands-v0 0.2.8+b4f4f6cd60 via fabric
> 	- fabric-containers-v0 0.1.21+d7c144a860 via fabric
> 	- fabric-content-registries-v0 3.0.3+d82b939260 via fabric
> 	- fabric-convention-tags-v1 1.0.1+474e4f7960 via fabric
> 	- fabric-crash-report-info-v1 0.1.11+3ac43d9560 via fabric
> 	- fabric-dimensions-v1 2.1.17+2540745460 via fabric
> 	- fabric-entity-events-v1 1.4.8+d7c144a860 via fabric
> 	- fabric-events-interaction-v0 0.4.19+d7c144a860 via fabric
> 	- fabric-events-lifecycle-v0 0.2.14+d7c144a860 via fabric
> 	- fabric-game-rule-api-v1 1.0.13+d7c144a860 via fabric
> 	- fabric-item-api-v1 1.4.0+4457765560 via fabric
> 	- fabric-item-groups-v0 0.3.11+91896a4960 via fabric
> 	- fabric-key-binding-api-v1 1.0.12+54e5b2ec60 via fabric
> 	- fabric-keybindings-v0 0.2.10+b4f4f6cd60 via fabric
> 	- fabric-lifecycle-events-v1 2.0.3+2d83e92c60 via fabric
> 	- fabric-loot-tables-v1 1.0.11+d7c144a860 via fabric
> 	- fabric-mining-level-api-v1 2.1.0+81ea5b3c60 via fabric
> 	- fabric-models-v0 0.3.6+d7c144a860 via fabric
> 	- fabric-networking-api-v1 1.0.21+d882b91560 via fabric
> 	- fabric-networking-v0 0.3.8+b4f4f6cd60 via fabric
> 	- fabric-object-builder-api-v1 2.1.0+fe4ddef060 via fabric
> 	- fabric-particles-v1 0.2.12+526dc1ac60 via fabric
> 	- fabric-registry-sync-v0 0.9.8+0d9ab37260 via fabric
> 	- fabric-renderer-api-v1 0.4.13+d882b91560 via fabric
> 	- fabric-renderer-indigo 0.5.0+7faf0d8860 via fabric
> 	- fabric-renderer-registries-v1 3.2.11+b4f4f6cd60 via fabric
> 	- fabric-rendering-data-attachment-v1 0.3.7+d7c144a860 via fabric
> 	- fabric-rendering-fluids-v1 2.0.2+54e5b2ec60 via fabric
> 	- fabric-rendering-v0 1.1.13+b4f4f6cd60 via fabric
> 	- fabric-rendering-v1 1.10.7+54e5b2ec60 via fabric
> 	- fabric-resource-conditions-api-v1 2.0.3+91b7aa6660 via fabric
> 	- fabric-resource-loader-v0 0.4.18+2de5574560 via fabric
> 	- fabric-screen-api-v1 1.0.10+d882b91560 via fabric
> 	- fabric-screen-handler-api-v1 1.2.0+1f6558e860 via fabric
> 	- fabric-textures-v0 1.0.12+3ac43d9560 via fabric
> 	- fabric-transfer-api-v1 1.6.0+2373a54560 via fabric
> 	- fabric-transitive-access-wideners-v1 1.0.0+bd8a4a1860 via fabric
> 	- fabricloader 0.14.5
> 	- java 17
> 	- minecraft 1.18.2
> [20:59:52] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/D:/Minecraft/.minecraft/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
> [20:59:52] [main/INFO]: Compatibility level set to JAVA_16
> [20:59:53] [main/WARN]: Configuration conflict: there is more than one oshi.properties file on the classpath
> [20:59:53] [main/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
> [20:59:54] [main/WARN]: Method overwrite conflict for method_5800 in carpet-fixes.mixins.json:itemFixes.ItemEntity_lightningKillsDropsMixin from mod carpet-fixes, previously written by carpet.mixins.ItemEntityMixin. Skipping method.
> [20:59:57] [main/ERROR]: Minecraft has crashed!
> net.fabricmc.loader.impl.FormattedException: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1493 failed
> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.5.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.5.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.5.jar:?]
> Caused by: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1493 failed
> 	at net.minecraft.class_1299.<clinit>(class_1299.java:269) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_3103.<clinit>(class_3103.java:28) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_3031.<clinit>(class_3031.java:83) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_6800.<clinit>(class_6800.java:20) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_6803.method_39702(class_6803.java:23) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_5458.method_30566(class_5458.java:86) ~[client-intermediary.jar:?]
> 	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
> 	at net.minecraft.class_5458.<clinit>(class_5458.java:85) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_2378.<clinit>(class_2378.java:291) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[client-intermediary.jar:?]
> 	at net.minecraft.client.main.Main.main(Main.java:153) ~[1.18.2-Fabric%200.14.5.jar:?]
> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460) ~[fabric-loader-0.14.5.jar:?]
> 	... 2 more
> Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1493 failed
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:418) ~[fabric-loader-0.14.5.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:322) ~[fabric-loader-0.14.5.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.5.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.5.jar:?]
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
> 	at net.minecraft.class_1299.<clinit>(class_1299.java:269) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_3103.<clinit>(class_3103.java:28) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_3031.<clinit>(class_3031.java:83) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_6800.<clinit>(class_6800.java:20) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_6803.method_39702(class_6803.java:23) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_5458.method_30566(class_5458.java:86) ~[client-intermediary.jar:?]
> 	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
> 	at net.minecraft.class_5458.<clinit>(class_5458.java:85) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_2378.<clinit>(class_2378.java:291) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[client-intermediary.jar:?]
> 	at net.minecraft.client.main.Main.main(Main.java:153) ~[1.18.2-Fabric%200.14.5.jar:?]
> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460) ~[fabric-loader-0.14.5.jar:?]
> 	... 2 more
> Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
> 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:413) ~[fabric-loader-0.14.5.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:322) ~[fabric-loader-0.14.5.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.5.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.5.jar:?]
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
> 	at net.minecraft.class_1299.<clinit>(class_1299.java:269) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_3103.<clinit>(class_3103.java:28) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_3031.<clinit>(class_3031.java:83) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_6800.<clinit>(class_6800.java:20) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_6803.method_39702(class_6803.java:23) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_5458.method_30566(class_5458.java:86) ~[client-intermediary.jar:?]
> 	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
> 	at net.minecraft.class_5458.<clinit>(class_5458.java:85) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_2378.<clinit>(class_2378.java:291) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[client-intermediary.jar:?]
> 	at net.minecraft.client.main.Main.main(Main.java:153) ~[1.18.2-Fabric%200.14.5.jar:?]
> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460) ~[fabric-loader-0.14.5.jar:?]
> 	... 2 more
> Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Variable modifier method modifyAmount(F)F in carpet-fixes.mixins.json:entityFixes.WolfEntity_snowballDamageMixin from mod carpet-fixes failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap carpet-fixes-refmap.json
> 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1385) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:413) ~[fabric-loader-0.14.5.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:322) ~[fabric-loader-0.14.5.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.5.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.5.jar:?]
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
> 	at net.minecraft.class_1299.<clinit>(class_1299.java:269) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_3103.<clinit>(class_3103.java:28) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_3031.<clinit>(class_3031.java:83) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_6800.<clinit>(class_6800.java:20) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_6803.method_39702(class_6803.java:23) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_5458.method_30566(class_5458.java:86) ~[client-intermediary.jar:?]
> 	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
> 	at net.minecraft.class_5458.<clinit>(class_5458.java:85) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_2378.<clinit>(class_2378.java:291) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[client-intermediary.jar:?]
> 	at net.minecraft.client.main.Main.main(Main.java:153) ~[1.18.2-Fabric%200.14.5.jar:?]
> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460) ~[fabric-loader-0.14.5.jar:?]
> 	... 2 more
> 

**Suplement**
I am quite not good at English. Pls ask me if you can't understand my words. 
I am also not good at English manners. Excuse me.

**Comment by FxMorin** [comment]
The Fix: https://github.com/fxmorin/carpet-fixes/issues/64#issuecomment-1121782249
I'll be making a new release tomorrow

**Comment by WOCOWZj** [comment]
Thhhhhhhhhhhhhhhhhhhhhhhhhhx
It works !!!
I don’t know how to express that lol

I can try item shadowing in my 1.18 world now, haha!

从 Windows 版邮件发送

发件人: Fx Morin
发送时间: 2022年5月11日 13:35
收件人: fxmorin/carpet-fixes
抄送: WOCOWZj; Author
主题: Re: [fxmorin/carpet-fixes] Game Crashes (Issue #66)

Closed #66.
