### ISSUE TITLE
Comparator Update Fix

### ISSUE THREAD

**Issue by angrynerd** [fxmorin/carpet-fixes#7]
I just started running this mod on my server. On the first load my users reported that they could break blocks but nothing would drop. This was solved by disabling the comparator update fix rule, though i dont know why that would cause it. Another user reported an issue where they would recieve a new chest everytime they opened one but i cant figure out what was causing this as i havent been able to reproduce it myself or with them. IN my testing to figure out which rule caused these problems i disabled all of the rules i had enabled and enabled each one by one as to figure out which one did it.

**Comment by angrynerd** [comment]
The chest issue also produced glitches like this which i also am now unable to reproduce for some reason. 
![2021-05-23_18 41 23](https://user-images.githubusercontent.com/24483958/119279442-d33a5b80-bbf9-11eb-8821-e178007f1e49.png)

**Comment by fxmorin** [comment]
I have a very strong feeling that carpet-fixes is not doing that, are there any other mods on the server?

**Comment by angrynerd** [comment]
Yes there are other mods like lithium, phosphor, hydrogen, etc. That being said it must be a pretty interesting conflict if thats the case because turning the rule on and off turns on an off block drops in real time. I will test out the mods i use set by set and see if one of them is causing it.

**Comment by fxmorin** [comment]
Ok ill look into it as well, cause if you see the problem by using the command then it's most likely the fix

**Comment by angrynerd** [comment]
I have just tried it with only carpet and carpet fixes installed and the same problem happens consistently.

**Comment by fxmorin** [comment]
Fixed this issue in https://github.com/fxmorin/carpet-fixes/commit/d6ee4c14e7cf51d5061ffcc796944d8a3ab0622b
I'll prob make a release with it tomorrow
