### ISSUE TITLE
playerBlockCollisionUsingCenterFix causes all entities to be immune to magma blocks

### ISSUE THREAD

**Issue by SplendidAlakey** [fxmorin/carpet-fixes#70]
**Describe the bug**

Setting playerBlockCollisionUsingCenterFix to true will make every entity in the game (including the player) not to take any damage from standing on magma blocks.

**To reproduce:**

1. /carpet-fixes playerBlockCollisionUsingCenterFix true
2. Walk over magma blocks
3. Take no damage
4. Let any other entity walk over magma blocks - same result

**Expected behavior**

Entities that are not designed to be immune to magma blocks should take damage while walking on it.

**Minecraft Version:**
 - 1.18.2
**Carpet-Fixes Version:**
 - v1.7.9
**Carpet Version:**
 - v1.4.69

**Logs**

https://gist.github.com/Footage2-Amply-Pounce/ce6cbbf89dfeda8e81e81d39b18d44a2 (seems to be nothing useful in there, but including it just in case)

**Comment by FxMorin** [comment]
Oh I like this one, ill take a look later ~~today~~ _been busy_
