### ISSUE TITLE
Incompatible with Recipe Cache

### ISSUE THREAD

**Issue by PweSol** [fxmorin/carpet-fixes#72]
**Please link the github for the mod that does not work, if known!**
https://gitlab.com/biom4st3r/optimizedcrafting

[minecraft.log](https://github.com/fxmorin/carpet-fixes/files/8747757/minecraft.log)

**Comment by PweSol** [comment]
Btw. carpet-fixes has `optimizedFurnaces` and `optimizedRecipeManager`. Are these better/same as Recipe Cache? Because if so, then Recipe Cache is redundant. Although `optimizedFurnaces` is limited to `<1.19-alpha.22.12.a`. Does that mean 1.19 has its own optimizations which are better/same as the method in carpet-fixes?

**Comment by FxMorin** [comment]
Correct `optimizedFurnaces` and `optimizedRecipeManager` give better performance then the simple caching provided by that mod.
Also 1.19 adds caching to furnaces ;)

**Comment by PweSol** [comment]
Do you know of any other popular performance mods that are redundant thanks to carpet-fixes? Also, do these performance improvements conflict with the likes of Lithium? I feel like vanilla optimizations that carpet-fixes has should be included in Lithium by default. Some of the optimizations here break vanilla parity, yes, and these shouldn't be in Lithium. But other are stated in the description to be vanilla friendly and are recommended to be used.
