### ISSUE TITLE
[Question] Is there a way to enable/disable all at once?

### ISSUE THREAD

**Issue by ardissaps** [fxmorin/carpet-fixes#74]
As enabling it all 1 by 1 is...

**Comment by FxMorin** [comment]
No that's in the works. Carpet does not currently have a way to do this.
I'm working on a Carpet-Fixes v2.0 which will be able to tho.

I should probably make a config file with them all enabled by default...

**Comment by ardissaps** [comment]
> 

okay sir, thx. Mod Menu integration would be amazing

**Comment by FxMorin** [comment]
It's server-side, so not really possible. The v2 will have a client-side system tho

**Comment by ardissaps** [comment]
> It's server-side, so not really possible. The v2 will have a client-side system tho

Good to hear, I hope it will be release before my next barber visit, hahaha, have a nice day!

**Comment by ardissaps** [comment]
> It's server-side, so not really possible. The v2 will have a client-side system tho

Good to hear, I hope it will be release before my next barber visit, hahaha, have a nice day!

**Comment by FxMorin** [comment]
Ya probably not, it's going to take a very long time. I'm very busy
