### ISSUE TITLE
Flight Disabled in Singleplayer

### ISSUE THREAD

**Issue by jdw-mis** [fxmorin/carpet-fixes#79]
As part of the fix for [MC-90855](https://bugs.mojang.com/browse/MC-90855) Flight was enabled by default in Singleplayer. Your command for toggleFlightEnabled changes this so that by default flying is disabled in Singleplayer. This is leading to mods that add flight mechanics kicking players out of their own Singleplayer games when using those flight mechanics. While the command to allow flight does work, it was incredibly annoying tracking down the cause of the kicks; not to mention needing to edit the level.dat to allow commands.

**Comment by FxMorin** [comment]
Oh ya that's been fixed in my 1.19 branch

**Comment by jdw-mis** [comment]
Ah that explains it, I'm using the latest 1.18.2 build

**Comment by FxMorin** [comment]
Lol ya the 1.19 branch is not public yet

**Comment by ardissaps** [comment]
> Oh ya that's been fixed in my 1.19 branch

So you ditch 1.18.2 completely? :p
