### ISSUE TITLE
updateSuppressionCrashFix

### ISSUE THREAD

**Issue by Notoriousi** [fxmorin/carpet-fixes#82]
**Is your feature request related to a problem? Please describe.**
A crash when using reIntroduceInstantBlockUpdates

**Describe the solution you'd like**
The implementation that carpet had in 1.18.2 and below to fix non-player update suppression crashes

**Describe alternatives you've considered**
None

**Additional context**
Carpetmod has removed the rule updateSuppressionCrashFix since 1.4.77 and since with carpet-fixes you can re-introduce update suppression it would be nice to also prevent crashes

**Comment by FxMorin** [comment]
Ya thought about it, I might add it back in, ill see if I get time to do so
