### ISSUE TITLE
optimizedRecipeManager breaks suspicious stew crafting

### ISSUE THREAD

**Issue by DragonCrafted87** [fxmorin/carpet-fixes#85]
**Describe the bug**
Cannot Craft Suspicious Stew with optimizedRecipeManager turned on

**To Reproduce**
1. turn on Rule
2. try to craft suspicious stew in the player inventory

**Expected behavior**
Craft Suspicious Stew
 
**Minecraft Version:**
 - 1.19
**Carpet-Fixes Version:**
 - v1.9.1
**Carpet Version:**
 - v1.4.79

**Comment by FxMorin** [comment]
I'll look into it when I get the time
