### ISSUE TITLE
Carpet TCTC conflict

### ISSUE THREAD

**Issue by Aculoss** [fxmorin/carpet-fixes#87]
Conflicts with Carpet TCTC additions ObdisianPlatform mixin, causing a server crash.

**Comment by FxMorin** [comment]
Oh I see, we do some very similar things, and damn Hendrix thats one heck of a work around.
Carpet-Extensions really need some sort of API to get rules from other carpet extensions

**Comment by FxMorin** [comment]
Fixed in Carpet-TCTC-Addition
