### ISSUE TITLE
[MC-252439] - Cured Villager trades not refreshing (caused by empty `Brain`)

### ISSUE THREAD

**Issue by James103** [fxmorin/carpet-fixes#88]
**Does your bug have a Mojira id? If so, what is it?**
It's [MC-252439](https://bugs.mojang.com/browse/MC-252439)

**What's the bug about? Why do you want it fixed?**
When a villager converts to a Zombie Villager and vice versa, it loses all data inside its `Brain`. This data was kept on versions 1.18.2 and prior, but is lost in version 1.19.

This bug IS fixed in version 1.19.1, but that version has no planned release date nor is the pre-release for that version compatible with many mods.

**Describe the solution you'd like**
Some way to backport the fix for MC-252439 and import it into this mod.

**Describe alternatives you've considered**
A Scarpet app may be able to capture the `Brain` data right when a villager converts to a zombified villager and restore that data upon curing.

**What should the rule be called?**
`zombieVillagerBrainLossFix` (name subject to change)

**Comment by FxMorin** [comment]
I instead recommend you use https://github.com/apple502j/dotone
which has this built-in
