### ISSUE TITLE
projectileGoalTargetsDeadEntitiesFix stops snow golems from shooting completely

### ISSUE THREAD

**Issue by IAmSneak** [fxmorin/carpet-fixes#90]
Snow golems do not throw snowballs at mobs when projectileGoalTargetsDeadEntitiesFix is set to true

1. Set projectileGoalTargetsDeadEntitiesFix to true
2. Place a zombie next to a snow golem
3. It wont throw snowballs

**Minecraft Version:**
 - 1.19
**Carpet-Fixes Version:**
 - v1.10.0
**Carpet Version:**
 - 1.4.79+v22060

**Comment by FxMorin** [comment]
I think that rule was fixed in 1.19. So either I missed it or it broke due to something else. I'll check it once I get the time
