### ISSUE TITLE
entityBlockCollisionUsingCenterFix causes players at high heights to fall really fast

### ISSUE THREAD

**Issue by IAmSneak** [fxmorin/carpet-fixes#91]
entityBlockCollisionUsingCenterFix causes players at high heights to fall really fast. In the video i fall from y=448 to y=445 almost instantly. Also happens with other entities.

1. Create a world with a datapack to expand build height and go up really high
2. Set entityBlockCollisionUsingCenterFix to true
3. Look down and fall, youll see you fall quite quickly

Player should fall at a reasonable speed

[Video](https://youtu.be/Q29vB3StyN0)

**Minecraft Version:**
 - 1.19
**Carpet-Fixes Version:**
 - v1.10.0
**Carpet Version:**
 - 1.4.79+v22060

**Comment by FxMorin** [comment]
Weird this was fixed before, I guess I will look into it again
