### ISSUE TITLE
Incompat with VeryManyPlayers causing server crash

### ISSUE THREAD

**Issue by Tempest-5ky** [fxmorin/carpet-fixes#94]
**Describe the bug**
More or less what it says on the box! Server crashes and deadlocks on startup, presumably because of a mixin conflict with VMP

**To Reproduce**
1. Install Carpet, Carpet-fixes, and Very Many Players on a server
2. Start server
3. Crash and deadlock, server is unable to stop itself properly and has to be force-stopped (killed)

**Expected behavior**
No crash, server starts normally and both mods work as intended

**Screenshots**
n/a

**Minecraft Version:**
 - 1.18.2
**Carpet-Fixes Version:**
 - v1.7.9
**Carpet Version:**
 - v1.4.69

**Additional context**
Server did not generate a crashlog as it didn't properly stop, but here's the spot in the logs where it died: https://mclo.gs/oavKH2T

**Comment by FxMorin** [comment]
Should be fixed in the latest release

**Comment by Tempest-5ky** [comment]
Ahh, unfortunately that version is for 1.19 and i'm sticking with 1.18.2 for now! Was hoping that there was a fix available for that version but alas not.
Thank you!

**Comment by FxMorin** [comment]
I already released a 1.18.2 version with the fix. v1.7.10

**Comment by FxMorin** [comment]
Don't worry, I got u xD

**Comment by Tempest-5ky** [comment]
Ah! Must not have seen it, completely my bad tysm!

**Comment by Tempest-5ky** [comment]
Crashes with a "requires 1.19" error D:
I definitely grabbed the 1.18 one!

**Comment by FxMorin** [comment]
Just released v1.7.11 which should fix everything

**Comment by Tempest-5ky** [comment]
Thank you! Very sorry for the trouble, i really appreciate this

**Comment by FxMorin** [comment]
All good, have fun!
