### ISSUE TITLE
Conflict with Hey That's Mine

### ISSUE THREAD

**Issue by brokenshadows** [fxmorin/carpet-fixes#95]
**Describe the bug**
Mod conflicts with "Hey That's Mine" v1.1.5

**To Reproduce**

1. Install HTM from [https://modrinth.com/mod/htm/versions](url) and carpet-fixes (plus any dependencies)
2. Start server
3. Watch it catch on fire, and crash
4. Lament
5. Remove mods one-by-one until the server starts again
6. Remove carpet-fixes and try again to see the server loads fine
7. Put all previously removed mods back into mods folder (sans carpet-fixes) and make sure everything is still loading correctly
8. Rage against the Deus Ex Machina because you don't really know how to edit mods to fix the problem

**Expected behavior**
Would expect the mods to work together on the same server

**Screenshots**
![error](https://user-images.githubusercontent.com/993019/180618471-b6462200-6834-463f-9e4e-98f74ae63ffb.png)

**Minecraft Version:**
 - 1.19
**Carpet-Fixes Version:**
 - v1.19-1.11.0
**Carpet Version:**
 - v1.19-1.4.79+v220607

**Additional context**
The problem was fixed by commenting out **entityFixes.EnderDragonEntity_blockDropsMixin** from the list in the **carpet-fixes.mixins.json** as suggested by @Potatoboy (HTM author)

**Comment by FxMorin** [comment]
Lmao ya that's def not a good fix. Sounds like they are doing something sketch tho, ill take a look later
